import type { TimeEvent } from '../types';

/**
 * Generates an iCal (.ics) file for a TimeEvent and triggers download
 */
export function exportToICal(event: TimeEvent) {
    const start = new Date(event.targetDate);
    const end = new Date(start.getTime() + 3600000); // Default to 1 hour duration

    const formatDate = (date: Date) => {
        return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
    };

    const content = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//Time Matter//NONSGML v1.0//EN',
        'BEGIN:VEVENT',
        `UID:${event.id}@timematter.app`,
        `DTSTAMP:${formatDate(new Date())}`,
        `DTSTART:${formatDate(start)}`,
        `DTEND:${formatDate(end)}`,
        `SUMMARY:${event.name}`,
        `DESCRIPTION:${event.note || 'Generated by Time Matter app'}`,
        'END:VEVENT',
        'END:VCALENDAR'
    ].join('\r\n');

    const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${event.name}.ics`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
